# Generated by Django 5.0.6 on 2025-08-13 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('price', models.FloatField(max_length=5)),
                ('qty', models.IntegerField(max_length=20)),
                ('type', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=200)),
                ('brand', models.CharField(max_length=200)),
                ('mfgdate', models.DateTimeField(default='', max_length=255)),
                ('expdate', models.DateTimeField(default='', max_length=255)),
                ('image', models.CharField(default='', max_length=255)),
            ],
        ),
    ]
